version: 1
sessionName: SignalOcean
profiles:
  full:
    layout:
      columns:
        - rows: ["be", "fe"]
        - rows: ["git"]
    panes:
      be:
        name: "BE"
        dir: "/Users/sirwanafifi/Documents/Projects/signal/SOWebPlatform/backend/Signal.Web"
        cmd: "dotnet watch run"
      fe:
        name: "FE"
        dir: "/Users/sirwanafifi/Documents/Projects/signal/SOWebPlatform"
        cmd: "./run.sh -fp"
      git:
        name: "git"
        dir: "/Users/sirwanafifi/Documents/Projects/signal/SOWebPlatform"
        cmd: "lazygit"
