version: 2

project_name: devmod

builds:
  - id: devmod
    main: ./
    env: [CGO_ENABLED=0]
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ldflags: ["-s", "-w"]

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

brews:
  - name: devmod
    repository:
      owner: sirwanafifi
      name: homebrew-devmod
    commit_author:
      name: release-bot
      email: releases@example.com
    homepage: "https://github.com/sirwanafifi/devmod"
    description: "Manage development environments with tmux layouts and project profiles"
    license: "MIT"
    install: |
      bin.install "devmod"
    test: |
      system "#{bin}/devmod", "--help"
